/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'core',
        'react',
        'tailwind',
        'cli',
        'next',
        'vite',
        'print',
        'sign',
        'ua',
        'eslint',
        'font',
        'fonts',
        'chart',
        'svg-rasterize',
        'testing',
        'e2e',
        'examples',
        'docs',
        'wasm',
        'ci',
        'deps',
        'release',
        '',
      ],
    ],
    'subject-case': [2, 'never', ['upper-case', 'pascal-case', 'start-case']],
    'header-max-length': [2, 'always', 100],
  },
};
